# Generated by Django 3.2.3 on 2024-02-16 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20240208_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'default_related_name': 'favorites', 'verbose_name': 'избранное', 'verbose_name_plural': 'Избранное'},
        ),
    ]
