# Generated by Django 3.2.3 on 2024-02-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_favorites_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name': 'избранное', 'verbose_name_plural': 'Избранное'},
        ),
    ]
